export const APP_NAME = "OtterHub"
export const APP_TAGLINE = "像水獭一样藏好你的文件"
export const APP_CATEGORY = "私人云盘"
export const APP_DESC_EN = "A Serverless Personal Cloud Drive"
export const APP_DESC_CN = "基于 Cloudflare KV + Telegram Bot API 的免费私人云盘"
